In [7]:
import os
import pandas as pd

# Path to the folder containing the CSV files
folder_path = f'E:\\flipside\\Berachain\\small_files'

# List to hold dataframes
dataframes = []

# Loop through all files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.csv'):
        file_path = os.path.join(folder_path, filename)
        df = pd.read_csv(file_path)
        dataframes.append(df)

# Concatenate all dataframes
merged_df = pd.concat(dataframes, ignore_index=True)

# Save the merged dataframe to a new CSV file
merged_df.to_csv('bera_transactions_data.csv', index=False)

In [8]:
merged_df.head()

,Unnamed: 0,blockNumber,transactionHash,transactionIndex,address,user_address,topics0,topics1,topics2,topics3,log_data,logIndex,removed,token_ids,token_amounts
0,0,0xf4a5a,0xfebcac58642b11ceb85946deaa018895ad342397e10b...,0xf,0xd9c0d89a9196d29d7b840e8225e550705cc02aa0,0x722c8e2b51312a591fe0d20165f544799bf92004,0x4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e...,0x000000000000000000000000722c8e2b51312a591fe0...,0x00000000000000000000000000000000000000000000...,0x000000000000000000000000722c8e2b51312a591fe0...,0x00000000000000000000000000000000000000000000...,0x81,False,"[24, 27, 29]","[1, 1, 1]"
1,1,0xf4a5e,0xc4e3780468a7399bdf4bcace774a4c6250f37ea8e2d6...,0x2e,0xd9c0d89a9196d29d7b840e8225e550705cc02aa0,0xd4b8130df6e6ec6f8061e7dde103e09d25fb58e0,0x4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e...,0x000000000000000000000000d4b8130df6e6ec6f8061...,0x00000000000000000000000000000000000000000000...,0x000000000000000000000000d4b8130df6e6ec6f8061...,0x00000000000000000000000000000000000000000000...,0x1a5,False,[24],[1]
2,2,0xf4a6b,0xe5defa7697f23fa316d9bc60c277ae77b5e20ed71c36...,0x20,0xd9c0d89a9196d29d7b840e8225e550705cc02aa0,0xb129114fae2d533629d442657ea5bc1bca5a0364,0x4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e...,0x000000000000000000000000b129114fae2d533629d4...,0x00000000000000000000000000000000000000000000...,0x000000000000000000000000b129114fae2d533629d4...,0x00000000000000000000000000000000000000000000...,0x0,False,"[24, 27]","[1, 1]"
3,3,0xf4a6d,0x390cb75e55c3580d9e15ecec6386a96dcfa80d993e6d...,0x1b,0xd9c0d89a9196d29d7b840e8225e550705cc02aa0,0x028e7303fac7c1b83e4b86e0307794be244c4eb3,0x4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e...,0x000000000000000000000000028e7303fac7c1b83e4b...,0x00000000000000000000000000000000000000000000...,0x000000000000000000000000028e7303fac7c1b83e4b...,0x00000000000000000000000000000000000000000000...,0x2d,False,"[24, 26, 27]","[1, 1, 1]"
4,4,0xf4a6d,0x9d30fe4a811b72f8f634c455b260e22abb4f6f6b78b8...,0x22,0xd9c0d89a9196d29d7b840e8225e550705cc02aa0,0x22bfd88c7c452745bb768f0c6788f6f7dc2071f0,0x4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e...,0x00000000000000000000000022bfd88c7c452745bb76...,0x00000000000000000000000000000000000000000000...,0x00000000000000000000000022bfd88c7c452745bb76...,0x00000000000000000000000000000000000000000000...,0x54,False,"[30, 28, 24, 23, 33, 26, 27, 29, 15, 17]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"